# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pdcp_pb2 as pdcp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buffer.proto',
  package='stored',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x62uffer.proto\x12\x06stored\x1a\npdcp.proto\"i\n\x06stored\x12\'\n\x06\x62uffer\x18\x01 \x01(\x0b\x32\x17.stored.stored.SNBuffer\x1a\x36\n\x08SNBuffer\x12\x16\n\x03pdu\x18\x01 \x03(\x0b\x32\t.pdcp.pdu\x12\x12\n\nbufferSize\x18\x02 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[pdcp__pb2.DESCRIPTOR,])




_STORED_SNBUFFER = _descriptor.Descriptor(
  name='SNBuffer',
  full_name='stored.stored.SNBuffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pdu', full_name='stored.stored.SNBuffer.pdu', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bufferSize', full_name='stored.stored.SNBuffer.bufferSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=141,
)

_STORED = _descriptor.Descriptor(
  name='stored',
  full_name='stored.stored',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='stored.stored.buffer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STORED_SNBUFFER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=141,
)

_STORED_SNBUFFER.fields_by_name['pdu'].message_type = pdcp__pb2._PDU
_STORED_SNBUFFER.containing_type = _STORED
_STORED.fields_by_name['buffer'].message_type = _STORED_SNBUFFER
DESCRIPTOR.message_types_by_name['stored'] = _STORED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

stored = _reflection.GeneratedProtocolMessageType('stored', (_message.Message,), {

  'SNBuffer' : _reflection.GeneratedProtocolMessageType('SNBuffer', (_message.Message,), {
    'DESCRIPTOR' : _STORED_SNBUFFER,
    '__module__' : 'buffer_pb2'
    # @@protoc_insertion_point(class_scope:stored.stored.SNBuffer)
    })
  ,
  'DESCRIPTOR' : _STORED,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:stored.stored)
  })
_sym_db.RegisterMessage(stored)
_sym_db.RegisterMessage(stored.SNBuffer)


# @@protoc_insertion_point(module_scope)
