# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pdcp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pdcp.proto',
  package='pdcp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\npdcp.proto\x12\x04pdcp\"&\n\x03pdu\x12\x0e\n\x06RX_HFN\x18\x01 \x01(\x05\x12\x0f\n\x07PDCP_SN\x18\x02 \x01(\x05\"\x1e\n\x04pdcp\x12\x16\n\x03pdu\x18\x01 \x03(\x0b\x32\t.pdcp.pdu\"\x8c\x01\n\nmanageInfo\x12\x17\n\x0fMaximum_PDCP_SN\x18\x01 \x01(\x05\x12\x0e\n\x06RX_HFN\x18\x02 \x01(\x05\x12\x19\n\x11Reordering_Window\x18\x03 \x01(\x05\x12\x17\n\x0fNext_PDCP_RX_SN\x18\x04 \x01(\x05\x12!\n\x19Last_Submitted_PDCP_RX_SN\x18\x05 \x01(\x05\x62\x06proto3')
)




_PDU = _descriptor.Descriptor(
  name='pdu',
  full_name='pdcp.pdu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RX_HFN', full_name='pdcp.pdu.RX_HFN', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PDCP_SN', full_name='pdcp.pdu.PDCP_SN', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=58,
)


_PDCP = _descriptor.Descriptor(
  name='pdcp',
  full_name='pdcp.pdcp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pdu', full_name='pdcp.pdcp.pdu', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=90,
)


_MANAGEINFO = _descriptor.Descriptor(
  name='manageInfo',
  full_name='pdcp.manageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Maximum_PDCP_SN', full_name='pdcp.manageInfo.Maximum_PDCP_SN', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RX_HFN', full_name='pdcp.manageInfo.RX_HFN', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Reordering_Window', full_name='pdcp.manageInfo.Reordering_Window', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Next_PDCP_RX_SN', full_name='pdcp.manageInfo.Next_PDCP_RX_SN', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Last_Submitted_PDCP_RX_SN', full_name='pdcp.manageInfo.Last_Submitted_PDCP_RX_SN', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=233,
)

_PDCP.fields_by_name['pdu'].message_type = _PDU
DESCRIPTOR.message_types_by_name['pdu'] = _PDU
DESCRIPTOR.message_types_by_name['pdcp'] = _PDCP
DESCRIPTOR.message_types_by_name['manageInfo'] = _MANAGEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

pdu = _reflection.GeneratedProtocolMessageType('pdu', (_message.Message,), {
  'DESCRIPTOR' : _PDU,
  '__module__' : 'pdcp_pb2'
  # @@protoc_insertion_point(class_scope:pdcp.pdu)
  })
_sym_db.RegisterMessage(pdu)

pdcp = _reflection.GeneratedProtocolMessageType('pdcp', (_message.Message,), {
  'DESCRIPTOR' : _PDCP,
  '__module__' : 'pdcp_pb2'
  # @@protoc_insertion_point(class_scope:pdcp.pdcp)
  })
_sym_db.RegisterMessage(pdcp)

manageInfo = _reflection.GeneratedProtocolMessageType('manageInfo', (_message.Message,), {
  'DESCRIPTOR' : _MANAGEINFO,
  '__module__' : 'pdcp_pb2'
  # @@protoc_insertion_point(class_scope:pdcp.manageInfo)
  })
_sym_db.RegisterMessage(manageInfo)


# @@protoc_insertion_point(module_scope)
